### ISSUE TITLE
Handling embedded navigation

### ISSUE THREAD

**Issue by lwansbrough** [pressly/scene-router#15]
Lets say I have two top level scenes:
- `Welcome`
- `Categories`

I want `Categories` to be a component with a navigator. Sub scenes of `Categories` should be handled by the `Categories` component, but should still be understood as scenes by the router.
- `Welcome`
- `Categories`
  - `Trending`
  - `Top`
  - `New`

How can I do this? Based on how this router works (it replaces each scene entirely with it's child when navigating through sub scenes) I was thinking I could specify that a scene and it's sub-scenes all use the same component, and I could pass props into each of the children, like so:

``` jsx
<Scene initialPath="/categories/trending" style={styles}>
  <Scene path="welcome" component={Welcome}/>
  <Scene path="categories" component={Categories}>
    <Scene path="trending" component={Categories} initialProps={{ page: Trending }}/>
  </Scene>
</Scene>
```

Perhaps that's logical, but the `Trending` component never receives the initial props anyway, so this isn't a solution I can use.

**Comment by lwansbrough** [comment]
As a work around for now I can do something like:

``` jsx
<Scene initialPath="/categories?category=trending" style={styles}>
  <Scene path="welcome" component={Welcome}/>
  <Scene path="categories" component={Categories}/>
</Scene>
```

Then have `Categories` manually manage it's children. Basically what that amounts to is that this scene router is really only good for single-level navigation and doesn't really solve any of the current complications of mobile routing with regards to sub-navigation.

**Comment by alinz** [comment]
@lwansbrough, One of the things that we did try in out experiment is nested components. It is possible but since Mobile screen is too small we found ourself doing too much. As you describe in your second post, we are doing the same thing and remove the nested child. 

One other thing is that initialProps only can be acceptable to very first Scene component. This is a design decision to make thing more predictable. 

We are constantly evolving the scene-router, and more use cases are more than welcome. and thanks for giving us feedback!

**Comment by sunny-g** [comment]
@lwansbrough can you elaborate on what you mean by this:

> Basically what that amounts to is that this scene router is really only good for single-level navigation and doesn't really solve any of the current complications of mobile routing with regards to sub-navigation.

I'm probably misunderstanding your assertion, but aren't you solving the issue of sub-navigation by parsing the path from the URL within your `Categories` component?

**Comment by lwansbrough** [comment]
@sunny-g Yeah I could handle that myself - but it would be nice if _somehow_ this was managed automatically by the router. For instance, it could be made such that each route would remove the part of the URI that it was handling, and would set a prop on itself with the remaining fragment. Then logic could be added in that route's component like:

``` javascript
switch (this.props.remainingRoute) {
  case '/trending':
    ...
}
```

**Comment by alinz** [comment]
@lwansbrough The new version of scene-router removes the nested component. To be honest with you, nested routes sounds cool but turns out to not that useful in mobile app. Also with the new release you can easily implement tabs with scene-router by using `AreaList` component.

I'm closing this ticket but if you want you can keep the conversion here.
